/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax;

import fr.unice.polytech.si5.polycreate.concretesyntax.PolycreateStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PolycreateStandaloneSetup extends PolycreateStandaloneSetupGenerated {
  public static void doSetup() {
    new PolycreateStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
