/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax.ide;

import fr.unice.polytech.si5.polycreate.concretesyntax.ide.AbstractPolycreateIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PolycreateIdeModule extends AbstractPolycreateIdeModule {
}
