/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PolycreateRuntimeModule extends AbstractPolycreateRuntimeModule {
}
