/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PolycreateStandaloneSetup extends PolycreateStandaloneSetupGenerated {

	def static void doSetup() {
		new PolycreateStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
