/**
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax.ui;

import fr.unice.polytech.si5.polycreate.concretesyntax.ui.AbstractPolycreateUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PolycreateUiModule extends AbstractPolycreateUiModule {
  public PolycreateUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
