/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax.ide


/**
 * Use this class to register ide components.
 */
class PolycreateIdeModule extends AbstractPolycreateIdeModule {
}
