/*
 * generated by Xtext 2.14.0
 */
package fr.unice.polytech.si5.polycreate.concretesyntax.ui.tests;

import com.google.inject.Injector;
import fr.unice.polytech.si5.polycreate.concretesyntax.ui.internal.ConcretesyntaxActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PolycreateUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ConcretesyntaxActivator.getInstance().getInjector("fr.unice.polytech.si5.polycreate.concretesyntax.Polycreate");
	}

}
